//! R1CS Optimizer - Reduce constraint systems through pattern-based transformations.
//!
//! This library provides tools to analyze and optimize R1CS (Rank-1 Constraint Systems)
//! generated by arkworks. It identifies patterns in constraints and applies
//! semantically-preserving transformations to reduce the constraint count.
//!
//! # Architecture
//!
//! The optimizer is built around **reduction passes** - modular units that:
//! 1. **Scan** the constraint matrix for specific patterns
//! 2. **Report** what they found (informative layer)
//! 3. **Reduce** patterns to their optimal form (transformation layer)
//!
//! # Example
//!
//! ```ignore
//! use ark_bn254::Fr;
//! use ark_relations::r1cs::ConstraintSystem;
//! use r1cs_optimizer::{Optimizer, OptimizerConfig};
//!
//! // Create your circuit
//! let cs = ConstraintSystem::<Fr>::new_ref();
//! my_circuit.generate_constraints(cs.clone())?;
//! cs.finalize();
//!
//! // Optimize
//! let optimizer = Optimizer::from_cs(cs);
//! let result = optimizer.optimize();
//!
//! println!("Reduced {} → {} constraints ({:.1}% reduction)",
//!     result.original_constraints,
//!     result.final_constraints,
//!     result.reduction_percentage());
//!
//! // Use the optimized matrix
//! let optimized_matrix = result.matrix;
//! ```
//!
//! # Available Reduction Passes
//!
//! | Pass | Pattern | Transformation |
//! |------|---------|----------------|
//! | `DeduplicationPass` | Identical constraints | Remove duplicates |
//! | `ConstantFoldingPass` | `c1 * c2 = c3` | Verify and remove |
//! | `LinearSubstitutionPass` | `1 * expr = var` | Inline expression |
//! | `DeadVariablePass` | Unused definitions | Remove constraint |
//! | `CommonSubexpressionPass` | Repeated terms | Report opportunities |

mod constraint;
mod reduction;
mod optimizer;
mod passes;

// Core types
pub use constraint::{Constraint, ConstraintMatrix, LinearCombination, Term};

// Reduction infrastructure
pub use reduction::{
    MatchMetadata, OptimizationResult, PatternMatch, PatternType,
    ReductionPass, ReductionReport,
};

// Optimizer
pub use optimizer::{MatrixStats, Optimizer, OptimizerConfig};

// Individual passes
pub use passes::{
    CommonSubexpressionPass, ConstantFoldingPass, DeadVariablePass,
    DeduplicationPass, LinearSubstitutionPass,
};

/// Re-export ark types for convenience.
pub mod ark {
    pub use ark_ff::PrimeField;
    pub use ark_relations::r1cs::{ConstraintSynthesizer, ConstraintSystemRef, SynthesisError};
}

// Legacy compatibility - keep old names working
#[doc(hidden)]
#[deprecated(since = "0.2.0", note = "Use `Optimizer` instead")]
pub type Analyzer<F> = Optimizer<F>;

#[doc(hidden)]
#[deprecated(since = "0.2.0", note = "Use `OptimizerConfig` instead")]
pub type AnalysisConfig = OptimizerConfig;
